# Generated by Django 5.0.2 on 2024-03-04 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=3)),
                ('gender', models.CharField(choices=[('m', 'M'), ('f', 'F')], max_length=1)),
                ('age_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('description', models.CharField(max_length=300)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
