# Generated by Django 5.0.2 on 2024-02-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_students_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('students', models.ManyToManyField(blank=True, related_name='classes', to='students.student')),
            ],
        ),
    ]
